### ISSUE TITLE
小程序不是自带翻页组件 为啥还要单独做？

### ISSUE THREAD

**Issue by gundanx10** [lulusir/mpvue-slide#2]
<template>
  <div class="container">
    <swiper>
      <swiper-item class="item" v-for="(img, index) in item.imgs" :key="index">
        <img :src="img">
      </swiper-item>
    </swiper>
  </div>
</template>

**Comment by DestinyHunter** [comment]
因为小程序的不支持web啊

**Comment by lulusir** [comment]
是的，为了兼容h5和小程序
