### ISSUE TITLE
你好，我想提一个跟这个项目没关系的issues，如果您觉得不合适的话可以关闭~~

### ISSUE THREAD

**Issue by Yvan0329** [lulusir/mpvue-slide#3]
我看到您在mpvue的合作项目征集中，有个小程序ezchinese-，我体验了一下感觉效果特别棒，非常好看，您有开源吗~我想学习参考一下~~不知道可以吗~~

**Comment by lulusir** [comment]
@Yvan0329 那个是公司项目，不能开源
